apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    something: $(KREDIK_NAMESPACE).something.nowhere
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:$(KREDIK_IMAGE_TAG)
        ports:
        - containerPort: 80
