apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: kredik-env
    env: kredik.properties
vars:
  - name: IMAGE_TAG
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: kredik-env
    fieldRef:
      fieldpath: data.IMAGE_TAG
configurations:
  - var-reference.yaml