apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: KREDIK_NS_NAME
resources:
  - deployment.yaml
configMapGenerator:
  - name: kredik-env
    env: kredik.properties
vars:
  - name: KREDIK_IMAGE_TAG
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: kredik-env
    fieldRef:
      fieldpath: data.KREDIK_IMAGE_TAG
  - name: KREDIK_NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: kredik-env
    fieldRef:
      fieldpath: data.KREDIK_NAMESPACE
configurations:
  - var-reference.yaml