apiVersion: v1
kind: Service
metadata:
  labels:
    app: archiver
    component: archiver-api
  name: archiver-api
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: archiver
  type: ClusterIP
